/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:650394:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
  /*if (corrects >= 40) {
    points *= multiplier;
    sound2.trigger();
  } else {
    println("You do not have enough points!");
  }*/
  points *= multiplier;
    sound2.trigger();
} //_CODE_:imgButton1:650394:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:606910:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
  if (corrects >= 10) {
    multiplier += percent;
    corrects -= 10;
    sound2.trigger();
  } else {
    println("You do not have enough points!");
  }
} //_CODE_:imgButton2:606910:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:551517:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
  if (corrects >= 25) {
    corTilLevel /= 2;
    displayCTL /= 2;
    sound2.trigger();
  } else {
    println("You do not have enough points!");
  }
} //_CODE_:imgButton3:551517:

public void imgButton4_click1(GImageButton source, GEvent event) { //_CODE_:imgButton4:738876:
  println("imgButton4 - GImageButton >> GEvent." + event + " @ " + millis());
  corrects = 0;
  sound1.trigger();
} //_CODE_:imgButton4:738876:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  imgButton1 = new GImageButton(this, 440, 250, 50, 50, new String[] { "p1.png", "p1.png", "p1.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 570, 250, 50, 50, new String[] { "p2.png", "p2.png", "p2.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  imgButton3 = new GImageButton(this, 440, 350, 50, 50, new String[] { "p3.png", "p3.png", "p3.png" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  imgButton4 = new GImageButton(this, 570, 350, 50, 50, new String[] { "p4.png", "p4.png", "p4.png" } );
  imgButton4.addEventHandler(this, "imgButton4_click1");
}

// Variable declarations 
// autogenerated do not edit
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton imgButton3; 
GImageButton imgButton4; 